"""empty message

Revision ID: 0a139876de8a
Revises: 48b568729507
Create Date: 2016-08-04 12:32:34.133233

"""

# revision identifiers, used by Alembic.
revision = '0a139876de8a'
down_revision = '48b568729507'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('matchid', sa.Integer(), nullable=True),
    sa.Column('point', sa.String(length=100), nullable=True),
    sa.Column('rebound', sa.String(length=100), nullable=True),
    sa.Column('assist', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['matchid'], ['match.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('points', sa.String(length=100), nullable=True),
    sa.Column('rebounds', sa.String(length=100), nullable=True),
    sa.Column('assists', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_record')
    op.drop_table('match_record')
    ### end Alembic commands ###
