"""empty message

Revision ID: 48b568729507
Revises: eb15ecb969c0
Create Date: 2016-08-03 02:18:56.664920

"""

# revision identifiers, used by Alembic.
revision = '48b568729507'
down_revision = 'eb15ecb969c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('against', sa.String(length=100), nullable=True),
    sa.Column('where', sa.String(length=200), nullable=True),
    sa.Column('when', sa.String(length=100), nullable=True),
    sa.Column('matchinfo', sa.String(length=200), nullable=True),
    sa.Column('score_gnp', sa.Integer(), nullable=True),
    sa.Column('score_enemy', sa.Integer(), nullable=True),
    sa.Column('finish', sa.Boolean(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.Column('createdTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    ### end Alembic commands ###
