"""empty message

Revision ID: eb15ecb969c0
Revises: 83dfb143331d
Create Date: 2016-08-03 02:13:32.094090

"""

# revision identifiers, used by Alembic.
revision = 'eb15ecb969c0'
down_revision = '83dfb143331d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('createdTime', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'createdTime')
    ### end Alembic commands ###
