"""empty message

Revision ID: f2ee371e8280
Revises: None
Create Date: 2016-08-09 00:43:10.765154

"""

# revision identifiers, used by Alembic.
revision = 'f2ee371e8280'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_record', sa.Column('assist', sa.Integer(), nullable=True))
    op.add_column('match_record', sa.Column('point', sa.Integer(), nullable=True))
    op.add_column('match_record', sa.Column('rebound', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_record', 'rebound')
    op.drop_column('match_record', 'point')
    op.drop_column('match_record', 'assist')
    ### end Alembic commands ###
