"""empty message

Revision ID: ff5747fc1fe1
Revises: f2ee371e8280
Create Date: 2016-08-09 00:56:02.092463

"""

# revision identifiers, used by Alembic.
revision = 'ff5747fc1fe1'
down_revision = 'f2ee371e8280'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_record', sa.Column('points', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_record', 'points')
    ### end Alembic commands ###
